// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "components": {
        "schemas": {
            "github_com_ryan-truong_kms-wrapper_pkg_types.Chain": {
                "enum": [
                    "evm",
                    "cosmos"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "ChainEVM",
                    "ChainCosmos"
                ]
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.CosmosSignRequest": {
                "properties": {
                    "hrp": {
                        "type": "string"
                    },
                    "key_path": {
                        "example": "proj-a/prod/alice",
                        "type": "string"
                    },
                    "sign_doc": {
                        "description": "SignDoc is base64 protobuf bytes when sign_mode=DIRECT and raw JSON when sign_mode=AMINO_JSON.",
                        "type": "string"
                    },
                    "sign_mode": {
                        "enum": [
                            "DIRECT",
                            "AMINO_JSON"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "key_path",
                    "sign_doc",
                    "sign_mode"
                ],
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.EVMSignEIP712Request": {
                "properties": {
                    "eip712_digest": {
                        "pattern": "^(0x)?[0-9a-fA-F]{64}$",
                        "type": "string"
                    },
                    "key_path": {
                        "example": "proj-a/prod/alice",
                        "type": "string"
                    }
                },
                "required": [
                    "eip712_digest",
                    "key_path"
                ],
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.EVMSignPersonalMessageRequest": {
                "properties": {
                    "key_path": {
                        "example": "proj-a/prod/alice",
                        "type": "string"
                    },
                    "personal_message": {
                        "pattern": "^(0x)?[0-9a-fA-F]+$",
                        "type": "string"
                    }
                },
                "required": [
                    "key_path",
                    "personal_message"
                ],
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.EVMSignRawTxRequest": {
                "properties": {
                    "chain_id": {
                        "example": 1,
                        "minimum": 1,
                        "type": "integer"
                    },
                    "key_path": {
                        "example": "proj-a/prod/alice",
                        "type": "string"
                    },
                    "raw_tx": {
                        "pattern": "^(0x)?[0-9a-fA-F]+$",
                        "type": "string"
                    }
                },
                "required": [
                    "chain_id",
                    "key_path",
                    "raw_tx"
                ],
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse": {
                "properties": {
                    "error": {
                        "example": "unauthorized",
                        "type": "string"
                    }
                },
                "required": [
                    "error"
                ],
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyCreateRequest": {
                "properties": {
                    "chains": {
                        "example": [
                            "evm",
                            "cosmos"
                        ],
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.Chain"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "path": {
                        "example": "proj-a/prod/alice",
                        "type": "string"
                    }
                },
                "required": [
                    "path"
                ],
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyCreateResponse": {
                "properties": {
                    "already_existed": {
                        "example": false,
                        "type": "boolean"
                    },
                    "chains": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.Chain"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "cosmos_address": {
                        "type": "string"
                    },
                    "evm_address": {
                        "type": "string"
                    },
                    "path": {
                        "type": "string"
                    },
                    "public_key_hex": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyInfo": {
                "properties": {
                    "chains": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.Chain"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "cosmos_address": {
                        "type": "string"
                    },
                    "evm_address": {
                        "type": "string"
                    },
                    "path": {
                        "type": "string"
                    },
                    "public_key_hex": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyListEntry": {
                "properties": {
                    "chains": {
                        "description": "null = tag read failed (see resilient list)",
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.Chain"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "path": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyListResponse": {
                "properties": {
                    "count": {
                        "example": 2,
                        "type": "integer"
                    },
                    "keys": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyListEntry"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "next_cursor": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyUpdateChainsRequest": {
                "properties": {
                    "add_chains": {
                        "example": [
                            "cosmos"
                        ],
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.Chain"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.KeyUpdateChainsResponse": {
                "properties": {
                    "chains": {
                        "items": {
                            "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.Chain"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "path": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.SignResponse": {
                "properties": {
                    "cosmos_address": {
                        "type": "string"
                    },
                    "pub_key": {
                        "type": "string"
                    },
                    "signature": {
                        "type": "string"
                    },
                    "signature_parts": {
                        "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.SignatureParts"
                    },
                    "signed_tx": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_ryan-truong_kms-wrapper_pkg_types.SignatureParts": {
                "properties": {
                    "r": {
                        "type": "string"
                    },
                    "s": {
                        "type": "string"
                    },
                    "v": {
                        "type": "integer"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "description": "Bearer token authorization using Authorization: Bearer \u003ctoken\u003e.",
                "scheme": "bearer",
                "type": "http"
            }
        }
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "info": {
        "description": "REST gateway for health checks and multi-chain signing operations.",
        "title": "KMS Wrapper API",
        "version": "1.0"
    },
    "openapi": "3.0.3",
    "paths": {
        "/v1/health": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "Service Unavailable"
                    }
                },
                "security": [],
                "summary": "Gateway health status (alias of /readyz; deprecated)",
                "tags": [
                    "health"
                ]
            }
        },
        "/v1/keys": {
            "get": {
                "parameters": [
                    {
                        "description": "Optional path prefix",
                        "example": "proj-a/",
                        "in": "query",
                        "name": "prefix",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyListResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Forbidden"
                    },
                    "429": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List KMS keys by prefix",
                "tags": [
                    "keys"
                ]
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyCreateRequest",
                                "description": "Key create payload",
                                "summary": "body"
                            }
                        }
                    },
                    "description": "Key create payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyCreateResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Forbidden"
                    },
                    "429": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Create a KMS key",
                "tags": [
                    "keys"
                ]
            }
        },
        "/v1/keys/info": {
            "get": {
                "parameters": [
                    {
                        "description": "Key path (format: {project}/{environment}/{username})",
                        "example": "proj-a/prod/alice",
                        "in": "query",
                        "name": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyInfo"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Forbidden"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "429": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Show a KMS key",
                "tags": [
                    "keys"
                ]
            }
        },
        "/v1/keys/{path}": {
            "patch": {
                "parameters": [
                    {
                        "description": "Key path (format: {project}/{environment}/{username})",
                        "example": "proj-a/prod/alice",
                        "in": "path",
                        "name": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyUpdateChainsRequest",
                                "description": "Chain expansion payload",
                                "summary": "body"
                            }
                        }
                    },
                    "description": "Chain expansion payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.KeyUpdateChainsResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Forbidden"
                    },
                    "429": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Expand a KMS key's chain allow-list",
                "tags": [
                    "keys"
                ]
            }
        },
        "/v1/sign/cosmos": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.CosmosSignRequest",
                                "description": "Cosmos sign payload",
                                "summary": "body"
                            }
                        }
                    },
                    "description": "Cosmos sign payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.SignResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "429": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Sign Cosmos payload",
                "tags": [
                    "signing"
                ]
            }
        },
        "/v1/sign/evm": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "discriminator": {
                                    "mapping": {
                                        "eip712_digest": "#/components/schemas/types.EVMSignEIP712Request",
                                        "personal_message": "#/components/schemas/types.EVMSignPersonalMessageRequest",
                                        "raw_tx": "#/components/schemas/types.EVMSignRawTxRequest"
                                    },
                                    "propertyName": "type"
                                },
                                "oneOf": [
                                    {
                                        "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.EVMSignRawTxRequest",
                                        "description": "Raw-transaction payload",
                                        "summary": "rawTx"
                                    },
                                    {
                                        "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.EVMSignPersonalMessageRequest",
                                        "description": "Personal-message payload",
                                        "summary": "personalMessage"
                                    },
                                    {
                                        "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.EVMSignEIP712Request",
                                        "description": "EIP-712 digest payload",
                                        "summary": "eip712"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Raw-transaction payload | Personal-message payload | EIP-712 digest payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.SignResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "429": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_ryan-truong_kms-wrapper_pkg_types.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Sign EVM payload",
                "tags": [
                    "signing"
                ]
            }
        }
    },
    "servers": [
        {
            "url": "http://localhost:8080/"
        }
    ]
}
`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "KMS Wrapper API",
	Description:      "REST gateway for health checks and multi-chain signing operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
